# Generated by Django 3.0.8 on 2020-07-13 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20200713_1341'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name_plural': 'Subcategories'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('V', 'Vehicles'), ('P', 'Property'), ('ES', 'Electronics'), ('KFHB', 'Kids, Fashion, Health & Beauty'), ('ETS', 'Essentials'), ('HG', 'Home & Garden'), ('HS', 'Hobby & Sports'), ('S', 'Services'), ('E', 'Education'), ('BI', 'Business & Industry'), ('FA', 'Food & Agriculture'), ('O', 'Other')], max_length=5, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Subcategory'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='app.Category'),
        ),
    ]
