# Generated by Django 3.0.8 on 2020-07-13 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20200713_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dislike',
            name='product',
        ),
        migrations.AddField(
            model_name='dislike',
            name='product',
            field=models.ManyToManyField(to='app.Product'),
        ),
        migrations.RemoveField(
            model_name='like',
            name='product',
        ),
        migrations.AddField(
            model_name='like',
            name='product',
            field=models.ManyToManyField(to='app.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Subcategory'),
        ),
    ]
